/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/moz-c.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.55, 0]} scale={[0.86, 1.17, 0.83]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 2.04, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-0.15, 2.81, 0]} scale={0.21} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[0.13, 2.81, 0]} scale={0.21} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[-0.01, 2.92, 0]} scale={0.21} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['default']} position={[-0.84, 1.17, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.69} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['default']} position={[-0.42, -0.62, 0.01]} scale={0.69} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['default']} position={[0.4, -0.62, 0.01]} scale={0.69} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['default']} position={[1.65, 1.17, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.69} />
    </group>
  )
}

useGLTF.preload('/moz-c.gltf')
